quarkus.smallrye-openapi.info-title=API de gerenciamento de filmes
%dev.quarkus.smallrye-openapi.info-title=API de Filmes (desenvolvimento)
quarkus.smallrye-openapi.open-api-version=3.0.4
%test.quarkus.smallrye-openapi.info-title=API de Filmes (testes)
quarkus.smallrye-openapi.info-description=API de filmes da disciplina de Web Services da turma de TSI do SENAC...
quarkus.smallrye-openapi.info-terms-of-service=No terms
quarkus.smallrye-openapi.info-contact-email=techsupport@senac.com.br
quarkus.smallrye-openapi.info-contact-name=Senac TSI
quarkus.smallrye-openapi.info-contact-url=http://sp.senac.com.br
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.theme=outline
quarkus.smallrye-openapi.path=/docs

# CORS (Cross-Origin Resource Sharing)
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE

# Log Configuration (para mostrar queries SQL)
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n

# Cache configuration
quarkus.cache.caffeine.books-cache.expire-after-write=PT15S

# SECURITY CONFIGURATION (API Key for ApiKeyProtected Filter)
api.security.keys=SENAC-API-KEY-12345,CHAVE-DO-PROFESSOR,CHAVE-DO-ADMIN

# RATE LIMITING CONFIGURATION
api.ratelimit.limit=5
api.ratelimit.window.seconds=10

# --- CONFIGURAÇÃO DE BANCO DE DADOS H2 POR AMBIENTE ---

# Perfil DEV (Desenvolvimento local com hot reload) - Usamos H2 em memória (não persistente)
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:db_dev
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa
%dev.quarkus.hibernate-orm.database.generation=drop-and-create # Recria o schema e carrega o import.sql
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.mapping.finished-level=default

# Perfil PROD (Produção / Render) - Usamos H2 baseado em arquivo (persistente)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:./api_filmes_db;DB_CLOSE_DELAY=-1 # O Render precisa de um arquivo persistente
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.database.generation=update # Usa 'update' para manter os dados, mas cria as tabelas se não existirem
quarkus.hibernate-orm.log.sql=false # Desativa logs de SQL em produção
quarkus.hibernate-orm.mapping.finished-level=default